import { Mulish } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/reduxProvider";
import { Toaster } from "@/components/ui/sonner";

const mulish = Mulish({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "e-DigiHealth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={mulish.className} suppressHydrationWarning>
        <ReduxProvider>
          <Toaster position="top-right" richColors />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
